install.packages("dplyr")
install.packages("ggplot2")
install.packages("gridExtra")
install.packages("tidyverse")
install.packages("grid")
install.packages("installr")
install.packages("broom", type="binary")
install.packages("tidyr")
install.packages("splitstackshape")
install.packages("plyr")
install.packages("corrplot")
install.packages("caret")
install.packages("randomForest")
install.packages("ridge")

library(dplyr)
library(ggplot2)
library(gridExtra)
library(tidyverse)
library(grid)
library(installr)
library(dplyr)
library(splitstackshape)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(tidyverse)
library(grid)
library(corrplot)
library(caret)
library(randomForest)
library(ridge)
library(plyr)


source("cleaning_R.R")

source("analysis_R.R")

source("regression_R.R")

cleaning()
analysis()
regression()

